language: node_js
node_js:
  - '6.10'

services:
  - docker

cache:
  yarn: true
  directories:
    - node_modules

env:
  global:
    - secure: FPQy/qes2ooKQ1iSV/GcurkcnluPJti4AFwulls2R1CYlYjIColsS+TjblArU/Mk7BZQIbvTpZACMokOEGTkz9LM7m9fGrobdfv+rRP0sMfvsp+DboUZ5TRRbQ9nRrXk4++DujxuqkQsMdao78XDggH1+9MkDS/O9BrCqQMSvyHGZBGDjFqpRPYOExoVnDkXbIjOF371w+OLvxAGSJ+M/qGZmRk+ZJYhntu2iIUiwKMTtKwTUKZuVRAEwjSapDT4R2ydmr/dhzIEj6S05BMcfHIh4+RwlIrktuF5SHm8/U69FpEOs0JlPxPTiWSp6XUwRTYXtt4ZIQ42E7QToZWS4sTTb4x3No0MjcX7jg2BAiXBYI+572wfqJCEL6uNYvbbGBGSFmTmNtlmIT9iDT31Ren8ivUjtYKynVR4MElP1bd0HLlmHf4aqrQ7Ij8dljwquLimJpQYDu6L6zZ1s8pZ9XYigAsShtkcoYD4wcIUJoNBMmX1ANzOkXzHIp/J9ebLab5A9lkf6FsGHuCDZkjCUuLTmAWPs4LF+IS5GcGl5uZO0+oiJHJVxTYeekcE4nwAKEjVM7VeSYOObXIpw6nH3lrEofupsSOC1fpuznRjcuKfg+ek9ORktfW90y5oRoK73F7U9Brzw/NzZrYQjKNVyqiaJk89a9vSsPS7pXHXZBA=
    - secure: N86K8weTi+a7eeNhWU6Hw1pt80QcnMyY4xh7d7Ej+NRYxojLnFgeW6HyvqhVM0jlJgZieMldpzc8KVsv+cahlkdrWJrisT9/R3nuhQdPKrbp9+78FsE+YF7TS2eFT9WiwXWWUFTPVPjPwvIZXRw1MLC28UerrohVUA2K17HgVybC+kzlg/BOYwmnBJ8IOWCc0p1bZTaSwpSGHizRl7wpKuFUZA/zVqvjv5vMnl+HfPjHmtLItsl5DFaCl679qohuHOnr/lQbrqVtWVtHLPAlrKW+dCGvsABgmXfb9dnJfa3XvBvSQAQff966lDhphJoCncoyGvOrxafyKF6WTM7E60tB7oPop+K76vBfDNGOjo487i4krvXFiQkJLo/+WVhXVpDLknA5aPwzirJpZ9DZ0LVw9eA0qOPGctnTWektuPzFCmKPq6YBo+GUq48sD6m1TvhNxa1nOPJkP8hiVCdkjuGDpFuRT+GiTeV8OkhWMHD1rWuij6/e5O7N61DDsvBAwHlx9iqa5kNA5gQgcbvPy1CBEaY+Voa1sAuzjLXmdB02jkIzlMNA7PgsKZyrPaGH+SSd4MDshyqocqq/DzGMbffpqk1TZyN0rFZwGjKHVx9lmLOGmVWTad1LD/A7Yo7xUDD5USY3G7pxR1254VWB0lypiD50uDktD+grqFmF3s0=
    - secure: OcuzizP1s3Bso2x6e1azEmmAPYVKWnu5p8ED9Hu4dEV+Yz4kqZ9N2qi8mxAltHw0nDuFr0GzUWUdifb2xIjS9n8UcVWqom10aHgPLg8mmDtRINLtEUN91FbWZO7H6DU5rkdHp1tHCYlOTFLeyzItFo+U7AfAdQ5lhFzAsE+P9UIDzg0IQm2xtliCJvFPcjG/isC/iupU+0CGOHK7e6O4F1TsQI0c5jfXWV4qm46GfkXp6o0RITQDlCIiUuGfHTqzZ5T0yB6E1vybjd3gglkpID+ZTle0bgjl0gtLg0ZVETMxS9QtShZhw/UT1poNAK657SYqkrUTQxns4yT8JN+UG+KFwdCYlcmjT+U2k7QeKPHjRwzKx/tcMJrOAC7La+y35XTDB3WN++xEQQbeELeroGCKkApgzpQpbIiCjm8T22kob/n37DBTylyejM4CH2RiZ8EOoMJ9bQskmLkWwAvzkA38Bc35De92W/6g4GnE2DV83nuIysPuX7H+jGE7r4BPcKcKuATTbJ++LANBLMt/nu3tW37yNK68U48kRUpuiRZeDjJsKAZZDUZnhFRyR5SueZS6q9OqFYC0USs/PGCekxDTaD6HNANwA2UoczuGGF0xFsKeAAK5KVKpu7RIn5pbBxKlCO+81UFIW797WCbGJjrmjVpUV9HXEANVmwoPxgM=

before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash -s
  - export PATH="$HOME/.yarn/bin:$PATH"

script:
  - npm run test:ci

after_success: |
  set -e
  npm run coveralls
  if [ "$TRAVIS_BRANCH" == "master" ]; then
    chmod -R 755 node_modules/
    pip install --user awscli
    docker login -e="${DOCKER_EMAIL}" -u="${DOCKER_USERNAME}" -p="${DOCKER_PASSWORD}"
  fi

before_deploy:
  - npm run dist

deploy:
  - provider: lambda
    zip: build/
    skip_cleanup: true
    function_name: ecd
    description: Deploy AWS ECS Services
    module_name: index
    handler_name: handle
    role: arn:aws:iam::608300940987:role/lambda-ecd
    runtime: nodejs6.10
    memory_size: 128
    timeout: 60
    region: eu-west-1
    access_key_id:
      secure: momo3E9AcX4mQfiHgDZ+cCN+aqsBmPCUBIwpFYFNPnqW0BH6EDmNyYRIosu33PI8U3wHXA4S5wxafajyf/+srL21JmRneKqI7Q3jPznlXPGPBDfrFAOm3pkOmjeOaOoAix4uYi/FLZ+BkI0bK8b728+gw7rUCgEHDry64Vqnvg8CQFWBO508VpUfNaB8rU1+edmWRhFf0oai4Lc/qec4ssbcdEClrb32bBm0TItbAArp6AShys9Eb/azQji9bZ1M2J4854XRDtX2O5OwtRAGGmKiXKh+C01iypAIPNV3+DBDLCSog4ExnE83tNJI68kWiuo8ShRdvVEwJzab76A4lJ5qlyM7qn1SgsCS4nhjAh/MOqdysJ8v8I95bp3a4EsYoHAFwZ91+s/cpOPCCYAbZEOUTDrVV6AkqaGN8vpR+qmCHkJ6GPcEuxv0AXZBDcpJIgkp/FxdDmNRrCm8QXleCHi2BzRs22EQRVxIJRRM0NbVcZjhBlUPyBCfv2fplsQoayurWUzPIjuLchghkCy6usm2uYLAYMyP1852Ym5skGWHNaZn7yIk53taQ5gOUaZ3XHDzu4DSNAGR4/3SU8NCOMAkye/zO+isHPtwHaV+Da0MIPSCQSpHLZleAe2eNb3BtWjK1qSU1vUoAyEXQzTwsiVVkTm8u2XWPOnMAVd576w=
    secret_access_key:
      secure: bFm2b4nDaYu2HU57m0pAZBhL4XXeJl8A3lwtdE3DGS2sFrMqi3aZiOpQnmnHo+Ua8XbEwjtV/VMb03+gYxy+XNhiOe1gm9CIHNX6q31MAkd8W0X3O1K1S0X+NUNArLsclRYt2ylCU0mTlPK8K4nHYaKiNZYwQJEcutI7DT0xGim5YFwcPHokB29z0XabB+gFoV4ET+8GvZp71pQ5ogBLrvaJTn1XolOzKyMTPWRM2AL5YKNQMEajRnaqgXEwS2+Df2dHOqRYvuQv/t4B11c/j7Y5TIxFgbt+8Di8/QnuBqOTT2JayVHIid1XcSzGIgkcUw71dYXe7Z3/vx5XsJi0k2QzEXxTrD+nRqHaA7LyfTXPpg6mIDlEXv4YaM0A2HXQy4bOYBTHXLz3frz658RQaMz+DXmd17oH3oGobiF5Wi375ciUKz5tip+0w4RI/xzQwJjA3vxTMFJvpjRHevkczoHCPs9o54CwcXSOa6lVuQUzm8FvUUx5vnMKj4EJbXicbmOToS5fxlFiI2PLe5pC9zowaYjt6tV9CRZLteqVnLvV9EIDDnj2IcahJlEpMxn4PXMBuTWNo1AK+2CyifLrypDEu35j8DCQ8m0YqusrOrkW7rkIpNzsE/DF/rRWHaPsOgNgKBNBABoaFgSvXADH2UyiVeQ/nR5t8D0Qzdgekg4=
    on:
      branch: master
  - provider: script
    skip_cleanup: true
    script: ./build-cli.sh
    on:
      branch: master
